### ISSUE TITLE
Attendance Scanner Terminal: Purchasing Hardware

### ISSUE THREAD

**Issue by bobron** [Team3128/info#18]
To make the terminal, we have decided that we will use a Rasberry Pi 3 with a 16x2 character LCD screen to replace the current Android Tablet based system. With the Pi, more people will be abel to program it and the infromation collected will (eventually) be able to be accessed in real time on Github.

+ [Adafruit Blue/White LCD Shield for Raspberry Pi](https://www.adafruit.com/products/1115)
+ [Raspberry Pi 3 Model B](https://www.adafruit.com/products/3055)

**Comment by chacha** [comment]
Hardware has been purchased.
