### ISSUE TITLE
San Diego Regional Logistics

### ISSUE THREAD

**Issue by chacha** [Team3128/info#4]
The San Diego Regional is coming up, and coordination to bring all our students there is incredibly important as they have created tough restrictions.

Administrative:

- [x] Pass out field trip permission forms to attendees (@MayaZivi)
- [x] Receive permission forms from attendees by Friday, February 26th (Tyler)
- [x] Send list of attendees to attendance and health (Tyler)
- [x] Create itinerary for San Diego Regional (@MayaZivi)

Transportation:

- [x] Find parent to transport robot/pit materials (@MayaZivi)
- [x] ~~Book UHaul Trailer for robot/pit material transport (Tyler)~~
- [ ] Get full list of students going and who needs rides (@MayaZivi)
- [ ] Get list of parents willing to provide transportation to others (@MayaZivi)
- [ ] Pair students needing rides with parents (@MayaZivi)

Food:

- [x] Decide on eating inside or outside the facility (???)
- [x] Create plan to execute above decision (expand task list) (???)

Robot:

- [x] Complete BOM/Cost Accounting Worksheet
- [x] Verify TIMS Roster against permission slips
- [x] Print Team Roster from TIMS (Tyler)
- [x] Update Driver Station

Questions, comments, concerns? Comment.

**Comment by MayaZivi** [comment]
Distilled info from email:

Parking
- Parking is free on Wednesday and Thursday in Main Lot
- Only get two parking passes ($10) on Friday/Saturday - these will probably be Tyler + Parent 
- People who can't get dropped off will carpool
- See email for parking instructions

Food
- Everyone bring lunches

Load-In
- Wednesday from 6-8PM
- 5 team members w/ safety glasses allowed

Women in Engineering
- Meeting on Friday at 1:30 for women on the team

Student Ambassadors
- Have two people sign up at Pit Admin

**To Do:**
- [ ] Get a roster of everyone attending 
- [ ] Tell people they're in charge of bringing their own food - there are vendors, they're just really expensive
- [ ] Start a carpool form to see who can't be dropped off and picked up
- [ ] Tell people about the Women in Engineering event
- [ ] Pick ambassadors/safety captain

**Comment by chacha** [comment]
We should try to find 6-8 people to load in with us on Wednesday. We need to pack on Wednesday and leave by 5-5:15ish for the Del Mar Fairgrounds.

**Comment by chacha** [comment]
@Garrison-Price Pointed out that we need to tell all students at the San Diego Regional that they need to keep their belongings on their person or in the stands. The pit will not be a storage location for personal belongings. There might be an exception for the pit crew.

**Comment by chacha** [comment]
@FreezingClouds Can you please ensure that our Driver Station has been updated to the latest version, as included in Team Update 12? You can then check off the item on this issue when its verified.

**Comment by FreezingClouds** [comment]
Yep, I updated that when I had to image the roboRIO

**Comment by chacha** [comment]
We're going to disassemble some shelves in the shed for the regional. Sometime before we go to Las Vegas we will get actual separate shelving.

**Comment by chacha** [comment]
We never ended up setting up a good carpool. Next year we also need to get a better stands section on Saturday filled with parents and students.
