### ISSUE TITLE
Internship Opportunities

### ISSUE THREAD

**Issue by tylerhcarter** [Team3128/info#9]
We should email the companies that sponsor us to look for internship opportunities. We just need to ask if they have an internship application and who they apply to.

Current companies to email:
- [x] Qualcomm
- [ ] ViaSat
- [ ] NASA
- [ ] Leidos
- [ ] Steve Price

Once we've emailed them, we should compile the opportunities and email them out to team members/post them on the info repo.

**Comment by chacha** [comment]
Tiffany has sent an email to Qualcomm re:Internships

**Comment by chacha** [comment]
Response from Qualcomm via @nguyentiff 

>sarah was right regarding the internships... only college students can apply for them, but i guess i'll 
> put the information i got from my uncle down below.
>
> What kind of internships do we provide?
> -We offer 3 month summer internships
> -Semester Schools - May to August
> -Quarter Schools - June to September
> Our primary focus for internships require a Computer Science / Computer Engineering / Electrical 
> Engineering degree
